// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // CLI-only (migrate, studio, introspect). The app's runtime client uses
  // DATABASE_URL (pooled) directly via the PrismaPg adapter. See src/lib/prisma.ts.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
